ALTER TABLE EMPLOYEE
DROP CONSTRAINT fk_POSITION;
ALTER TABLE EMPLOYEE
DROP CONSTRAINT fk_DEPTAA;
ALTER TABLE EMPLOYEE
DROP CONSTRAINT fk_QUALIF;
ALTER TABLE DEPTA
DROP CONSTRAINT fk_EMPLOYEE;

DROP TABLE DEPTA;

CREATE TABLE DEPTA (
  DepIDA        NUMBER(4)  NOT NULL,
  DEPTAName       VARCHAR2(50),
  Location       VARCHAR2(50),
  EmployeeId       NUMBER(4),
      CONSTRAINT DEPTAa_pk PRIMARY KEY (DepIDA)
);

DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (
  Employeeid         NUMBER(4)  NOT NULL,
  Lname              VARCHAR2(50),
  Fname              VARCHAR2(50),
  PositionId         NUMBER(4), 
  Supervisor         CHAR(5) DEFAULT NULL,
  HireDate           DATE,
  Salary             NUMBER(4),
  Commission         NUMBER(4) DEFAULT NULL,
  DEPTAId             NUMBER(4),
  QualId             NUMBER(4) DEFAULT NULL,
    CONSTRAINT emid_pk PRIMARY KEY (Employeeid)
);

DROP TABLE DEPENDENT;

CREATE TABLE DEPENDENT (
  EmployeeId        NUMBER(4)  NOT NULL,
  DenpendentId       NUMBER(4),
  DepDOB       DATE,
  Relation       VARCHAR2(50),
      CONSTRAINT depend_pk PRIMARY KEY (EmployeeId,DenpendentId)
);



DROP TABLE POSITION;

CREATE TABLE POSITION (
  PositionId         NUMBER(4)  NOT NULL,
  PosDesc            VARCHAR2(50),
      CONSTRAINT poid_pk PRIMARY KEY (PositionId)
);


DROP TABLE QUALIFICATION;

CREATE TABLE QUALIFICATION (
  QualId         NUMBER(4)  NOT NULL,
  QualDesc       VARCHAR2(50),
      CONSTRAINT quid_pk PRIMARY KEY (QualId)
);

DROP TABLE EMPLEVEL;

CREATE TABLE EMPLEVEL (
  Level_No         NUMBER(4)  NOT NULL,
  LowSalary        NUMBER(4),
  HighSalary       NUMBER(4),
      CONSTRAINT leid_pk PRIMARY KEY (Level_No),
	  CONSTRAINT chk_sal CHECK (LowSalary <= HighSalary)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_POSITION
FOREIGN KEY (PositionId) REFERENCES POSITION(PositionId);
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_DEPTAA
FOREIGN KEY (DEPTAId) REFERENCES DEPTA(DepIDA);
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_QUALIF
FOREIGN KEY (QualId) REFERENCES QUALIFICATION(QualId);
ALTER TABLE DEPTA ADD CONSTRAINT fk_EMPLOYEE
FOREIGN KEY (Employeeid) REFERENCES EMPLOYEE(Employeeid);